# Generated by Django 4.0.5 on 2022-06-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('c_slno', models.CharField(max_length=150)),
                ('c_name', models.CharField(max_length=150)),
                ('c_brand', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
