# Generated by Django 4.0.5 on 2022-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_slno', models.CharField(max_length=150)),
                ('cat_name', models.CharField(max_length=150)),
                ('cat_brand', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
